flaskapp/images/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed, FileSize
from wtforms import SubmitField

class UploadImageForm(FlaskForm):
    image = FileField("Allowed file types: .jpg, .jpeg, .png or .gif", 
                            validators = [FileRequired(), FileAllowed(['jpg', 'jpeg', 'png', 'gif']), 
                                FileSize(2*1024*1024, message="File must be less than 2 MB.")])
                            
                            
    submit = SubmitField('Upload')

flaskapp/images/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint,
                   current_app)
from flask_login import current_user, login_required
from flaskapp import db
from flaskapp.models import Image
from flaskapp.images.forms import UploadImageForm
from flaskapp.images.utils import save_image, upload_to_s3, delete_from_s3
import os

images_bp = Blueprint('images', __name__)

@images_bp.route("/upload", methods = ['GET', 'POST'])
@login_required
def upload():
    form = UploadImageForm()
    if form.validate_on_submit():
        image_file = save_image(form.image.data)
        # save to s3
        s3_url = upload_to_s3(image_file)
        # add to db
        image = Image(title=image_file, s3_path=s3_url, poster=current_user)
        db.session.add(image)
        db.session.commit()
        # delete it form the temp storage
        tmp_file = os.path.join(current_app.root_path, 'tmp_images', image_file)
        os.remove(tmp_file)
        flash('Upload Successful.', 'success')
        return redirect(url_for('images.images'))
    return render_template('upload.html', title='Upload an Image', form=form)

@images_bp.route("/images", methods = ['GET', 'POST'])
@login_required
def images():
    if current_user.is_authenticated:
        user_id = current_user.id
        images = Image.query.filter_by(user_id=user_id).all()
    return render_template('images.html', title='Images' , images=images)


@images_bp.route("/image/<int:image_id>")
@login_required
def image(image_id):
    if current_user.is_authenticated:
        user_id = current_user.id
        image_obj = Image.query.filter_by(user_id=user_id, id=image_id).first()
        if image_obj:
            image = Image.query.get_or_404(image_id)

    return render_template('image.html', title=image.title, image=image)


@images_bp.route("/image/<int:image_id>/delete", methods = ['POST'])
@login_required
def delete_image(image_id):
    image = Image.query.get_or_404(image_id)
    if image.poster != current_user:
        abort(403)
    # Delete from s3
    delete_from_s3(image.title)
    # Delete from db
    db.session.delete(image)
    db.session.commit()
    flash('Your image has been deleted.', 'success')
    return redirect(url_for('images.images'))

flaskapp/main/routes.py
from flask import render_template, request, Blueprint
from flaskapp.models import Image

main = Blueprint('main', __name__)

@main.route("/")
#@main.route("/home")
def home():
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db, bcrypt
from flaskapp.models import User, Image
from flaskapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskapp.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You can now log in.", 'success') # Second arg is bootstrap class
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods = ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

@users.route("/reset_password", methods = ['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("If an account with this email address exists, a password reset email will be sent shortly.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods = ['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You can now log in.", 'success') # Second arg is bootstrap class
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About the App</h1>
<hr>

<p class="gen">For details about the development of this app, please visit the 
    <a href="https://github.com/aeddeb/image-saver">github repo</a>.</p>

{%  endblock content %}

flaskapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="static/default_profile.jpg">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary"> {{ current_user.email }}</p>
        </div>
    </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
{%  endblock content %}

flaskapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1>Welcome to the Image Saver App!</h1>
<hr>
{% if current_user.is_authenticated %}
<p class="gen"> Great to see you {{ current_user.username }}! </p>
<p class="gen"> You are currently logged in. From the navigation bar above, you have the following options:</p>
  <ul>
    <li class="gen">View, download or delete your images</li>
    <li class="gen">Upload an image</li>
    <li class="gen">Update your username or email</li>
  </ul>

{% else %}
<p class="gen"> This app allows you to save your images into your own personalized gallery.</p>
<p class="gen">To create your own gallery, you first have to 
  <a href="{{ url_for('users.register') }}">register</a> and create your account.</p>
<p class="gen">If you already have an account, then you can <a href="{{ url_for('users.login') }}">log in</a>.</p>
{% endif%}
{% endblock content %}

flaskapp/templates/image.html
{% extends "layout.html" %}
{% block content %}

<h1>Image Preview</h1>
<hr>
<img src="{{ image.s3_path }}" style="width: 600px">
<br/>
<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ image.s3_path }}">Download</a>
<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Image?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action=" {{ url_for('images.delete_image', image_id=image.id )}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

<!-- Add a button to take back to gallery--> 
<br/>
<hr>
<a href="{{ url_for('images.images') }}">Back to Image Gallery</a>

{%  endblock content %}

flaskapp/templates/images.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
        <div class="col-lg-12">
            <h1 class="page-header">Image Gallery</h1>
        </div>
        <hr>
    {% if not images %}
        <p class="gen">Your gallery is currently empty. To start placing images into your gallery, 
            you can <a href="{{ url_for('images.upload') }}">upload</a>
            an image.</p>
    {% else %}    
        <p class="gen">
            Click on <i>View Image</i> on any image below to open an Image Preview. The Image Preview 
            page provides you with the options to download or delete the image.
        </p>
        <div class="row">
            {% for image in images %}
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <img class="gallery" src="{{ image.s3_path }}" width="250: px">
                <a href="{{ url_for('images.image', image_id=image.id) }}">View Image</a>
            </div>
            {% endfor %}
    </div>
    {% endif %}
</div>


{%  endblock content %}

flaskapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

    {% if title %}    
    <title>Image Saver - {{ title }}</title>
    {% else %}
    <title>Image Saver</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Image Saver</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <!-- <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a> -->
                <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('images.images')}}">Images</a>
                <a class="nav-item nav-link" href="{{ url_for('images.upload')}}">Upload</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-12"> <!--original was col-md-8 when there was the right side bar-->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
                {% endfor%}
              {% endif %}
            {% endwith%}
            {% block content %}{% endblock %}
          </div>
          <!--
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div> -->
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

flaskapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need to create an account? <a class="ml-2" href=" {{ url_for('users.register') }} ">Sign up now</a>
        </small>
    </div>
{%  endblock content %}

flaskapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}                
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href=" {{ url_for('users.login') }} ">Sign in</a>
        </small>
    </div>
{%  endblock content %}

flaskapp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{%  endblock content %}

flaskapp/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{%  endblock content %}

flaskapp/templates/upload.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action=" {{ url_for('images.upload') }}" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
    <legend class="border-bottom mb-4">Upload an Image</legend>
        <div class="form-group">
            {{ form.image.label() }}
            {{ form.image(class="form-control-file")}}
            {% if form.image.errors %}
                {% for error in form.image.errors %}
                    <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
            {% endif %}
        </div>
    </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
</form>
{%  endblock content %}